export const homeObjOne = {
    id: 'moneymoney',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: '2020-06-05',
    headline: 'moneymoney 프로젝트',
    description: 'Java와 Oracle DBMS로 개발한 자금관리 프로그램',
    buttonLabel: 'Learn More',
    imgStart: false,
    alt: 'moneymoney',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'note',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '2020-07-27',
    headline: 'note 프로젝트',
    description: 'JSP와 Apache Tomcat을 활용한 SNS 웹 애플리케이션',
    buttonLabel: 'Learn More',
    imgStart: true,
    alt: 'note',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'sapare',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topLine: '2020-11-12',
    headline: '사파리 프로젝트',
    description: 'Spring 프레임워크와 AJAX를 주요로 개발한 중고매매 웹 애플리케이션',
    buttonLabel: 'Learn More',
    imgStart: false,
    alt: 'sapare',
    dark: true,
    primary: true,
    darkText: false,
}